### PR TITLE
Migrate to Terraform SDK v1.0.0

### PR DESCRIPTION
**Pull request by joshgodsiff**

### CODE REVIEW

**Comment by comozo** [comment]
has this been tested ?

**Comment by Kheldar** [comment]
Tell me how to test it and I'll test it.

**Comment by lenfree** [comment]
could use https://github.com/packetloop/homebrew-mayhem/pull/15  (I previously did) as a reference perhaps

**Review by lenfree — APPROVED** [review]
Agora might need to be upgraded to TF >= 0.12 before we could use this.

**Pull request merged**
